FROM amazonlinux:@AMAZONLINUX_VERSION@

RUN yum -y update

RUN yum -y groupinstall "Development Tools"

RUN yum -y install \
      rubygems \
      ruby-devel \
      golang \
      openssl-devel \
      wget

RUN gem install \
      --no-ri \
      --no-rdoc \
      fpm

# Set up golang
ENV GOPATH=/root/go
RUN mkdir -p $GOPATH/bin
ENV PATH=$PATH:$GOPATH/bin

# Install glide
COPY glide-@GLIDE_VERSION@-linux-amd64.tar.gz.sha256sum /tmp
RUN cd tmp && \
      wget https://github.com/Masterminds/glide/releases/download/@GLIDE_VERSION@/glide-@GLIDE_VERSION@-linux-amd64.tar.gz && \
      sha256sum -c glide-@GLIDE_VERSION@-linux-amd64.tar.gz.sha256sum && \
      tar xzf glide-@GLIDE_VERSION@-linux-amd64.tar.gz && \
      mv linux-amd64/glide /usr/bin && \
      rm -rf glide-@GLIDE_VERSION@-linux-amd64.tar.gz linux-amd64 && \
      chown root:root /usr/bin/glide

RUN mkdir -p /rpmbuild/

COPY . /rpmbuild/

RUN make package -C /rpmbuild

# vim: set ft=Dockerfile:
