FROM amazonlinux:@AMAZONLINUX_VERSION@

RUN yum -y update

RUN yum -y groupinstall "Development Tools"

RUN yum -y install \
      rubygems \
      ruby-devel \
      golang \
      openssl-devel \
      wget

RUN gem install \
      --no-ri \
      --no-rdoc \
      fpm

# Set up golang
ENV GOPATH=/root/go
RUN mkdir -p $GOPATH/bin
ENV PATH=$PATH:$GOPATH/bin
RUN curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
COPY keepsake.yaml /etc

# vim: set ft=Dockerfile:
